[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "About"
url = ""
weight = 20
title = "Made with ❤️ by the VitalBand team"

[[main]]
identifier = "product"
name = "Product"
weight = 50

[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#github'/></svg>"
  url = ""
  weight = 10
  title = "Visit the GitHub project"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#twitter'/></svg>"
  url = ""
  weight = 20
  title = "Contact on Twitter"
